In [119]:
import pandas as pd
import numpy as np

In [9]:
#Question 1
pd.__version__

'2.2.2'

In [11]:
df = pd.read_csv(r'C:\Users\oxana\Documents\ДОРО\Аналитика данных\Zoomcamp\laptops.csv')

In [13]:
print(df.head())

                                              Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.

In [115]:
#Question 2
df.shape[0]

2160

In [17]:
#Question 3
unique_brands_count = df['Brand'].nunique()
print(unique_brands_count)

In [25]:
#Question 4
columns_with_na = df.isnull().sum()
num_columns_with_missing = (columns_with_na > 0).sum()
print(num_columns_with_missing)

3


In [27]:
#Question 5
dell_df = df[df['Brand'] == "Dell"]
max_final_price = dell_df['Final Price'].max()
print(max_final_price)

3936.0


In [51]:
#Question 6
median_screen = df['Screen'].median()
print(median_screen)

15.6


In [61]:
mode_value = df['Screen'].mode()[0]
print(mode_value)

15.6


In [67]:
df['Screen'].fillna(mode_value)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [69]:
print(df['Screen'].isnull().sum())

0


In [71]:
df['Screen'].median()

15.6

In [113]:
#Question 7
innjoo_df = df[df['Brand'] == "Innjoo"]
innjoo_df = innjoo_df[['RAM', 'Storage', 'Screen']]
print(innjoo_df.head())

In [79]:
#turn into numpy array
X = innjoo_df.to_numpy()

In [81]:
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [117]:
#matrix-matrix multiplication (XTX)
XTX = np.dot(X.T, X) #transpose X * X

#the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

#create the array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])

#compute w
X_T = X.T #transose X
w = np.dot(XTX_inv, X_T).dot(y) #inverse XTX * transpose X * y

# 7. Sum of all elements of w
result_sum = np.sum(w)
print(result_sum)

91.29988062995588
